# Generated by Django 2.2.5 on 2020-04-28 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0002_mypost_myprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypost',
            name='short_description',
            field=models.CharField(default='this is a short descripton to go in work.', max_length=240),
            preserve_default=False,
        ),
    ]
