# Generated by Django 2.2.5 on 2020-04-29 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0004_mypayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypayment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='covid.MyProfile'),
        ),
    ]
