# Generated by Django 2.2.5 on 2020-04-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0005_auto_20200430_0009'),
    ]

    operations = [
        migrations.CreateModel(
            name='FakeCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField()),
            ],
        ),
    ]
