# Generated by Django 2.2.5 on 2020-05-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0008_auto_20200505_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypost',
            name='main_pic',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mypost',
            name='pic_five',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mypost',
            name='pic_four',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mypost',
            name='pic_one',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mypost',
            name='pic_three',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mypost',
            name='pic_two',
            field=models.URLField(blank=True, null=True),
        ),
    ]
