# Generated by Django 2.2.5 on 2020-05-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0009_auto_20200505_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprofile',
            name='mail',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='phone_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
