# Generated by Django 2.2.5 on 2020-05-05 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0011_auto_20200505_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypayment',
            name='account_num',
            field=models.CharField(max_length=500),
        ),
    ]
